default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: mcacais22
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: event_me
test:
  <<: *default
  database: event_me

production:
  <<: *default
  database: event_me
